apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: m4g2bgy0i-nodejs-gitops
  description: This is GitOps manifest for m4g2bgy0i-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: m4g2bgy0i-nodejs
    janus-idp.io/tekton: m4g2bgy0i-nodejs
    backstage.io/kubernetes-id: m4g2bgy0i-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:m4g2bgy0i-nodejs
