apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m4g2bgy0i-nodejs
  janus-idp.io/tekton: m4g2bgy0i-nodejs
  backstage.io/kubernetes-id: m4g2bgy0i-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m4g2bgy0i-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
