apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: m4g2bgy0i-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:6b53c1a359a729a50f2d14d9f30b43d2852cb4de@sha256:870702f644334ab0091c046ff39e094fe332fa8e0f9180f35480a61f9df60bcc
          name: container-image
